receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp/data-prepper:
    endpoint: data-prepper:21890
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/data-prepper]