image:
  file: .gitpod.Dockerfile

tasks:
  - name: Backend
    init: |
      cd backend/src
      pyenv local 3.9.7
      poetry install
    command: poetry run uvicorn app.main:app --reload

  - name: Frontend
    init: |
      cd frontend/minor-illusion
      yarn install
    command: npm run dev

  - name: CockroachDB
    command: cockroach start-single-node --insecure

  # TODO: support CORS from gitpod url (noteableio-minorillusion-hash.xxx.gitpod.io)
  # - name: Jupyter
  #   init: |
  #     cd jupyter
  #     pyenv local 3.9.7
  #     poetry install
  #   command: poetry run jupyter notebook

  - name: Traefik
    command: traefik
      

  