version: '3.8'

services:
  backend1:
    build: ./backend
    ports:
      - 5678:5678
      - 8000:8000
    volumes:
      - ./backend/src/app:/usr/src/app
      - ./backend/src/tests:/usr/src/tests
      - ./backend/src/migrations/versions:/usr/src/migrations/versions
    environment:
      # ROOT_PATH: "/api"
      RUN_ALEMBIC: 1
      OTEL_SERVICE_NAME: "minor-illusion"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: grpc
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PYTHONASYNCIODEBUG: 1
    restart: always

  # backend2:
  #   build: ./backend
  #   volumes:
  #     - ./backend/src/app:/usr/src/app
  #     - ./backend/src/tests:/usr/src/tests
  #     - ./backend/src/migrations/versions:/usr/src/migrations/versions
  #   environment:
  #     ROOT_PATH: "/api"
  #   restart: always

  # proxy:
  #   image: traefik:latest
  #   volumes:
  #     - ./proxy:/etc/traefik
  #   ports:
  #     - 5000:5000
  #     - 8080:8080
    
  cockroach:
    image: cockroachdb/cockroach-unstable:v21.2.0-beta.4
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257

  # jupyter:
  #   build: ./jupyter
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - ./jupyter/notebooks:/home/jovyan/notebooks   
  #     - ./backend/src/app:/home/jovyan/backend/app:ro
  #   environment:
  #     PYTHONPATH: /home/jovyan/backend

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     # I'd love to just mount ./frontend/minor-illusion:/app
  #     # but it is volume hell with node_modules and .next directories
  #     - ./frontend/minor-illusion/src:/app/src
  #     - ./frontend/minor-illusion/public:/app/public
  #     - ./frontend/minor-illusion/package.json:/app/package.json
  #     - ./frontend/minor-illusion/yarn.lock:/app/yarn.lock
      
  # For logging and APM
  opensearch:
    image: opensearchproject/opensearch:2.1.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      
  dashboard:
    # Observability plugin and others are already installed, sanity check by 
    # exec'ing into container and `bin/opensearch-dashboards-plugin list`
    image: opensearchproject/opensearch-dashboards:2.1.0
    ports:
      - 5601:5601
    depends_on:
      - opensearch
    environment:
      OPENSEARCH_HOSTS: "https://opensearch:9200"
      DISABLE_INSTALL_DEMO_CONFIG: "true"

  data-prepper:
    image: opensearchproject/data-prepper:latest
    volumes:
      - ./opensearch/data-prepper-pipeline.yaml:/usr/share/data-prepper/pipelines.yaml
      #- ./opensearch/data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml
    depends_on:
      - opensearch

  otel-collector:
    image: otel/opentelemetry-collector:0.54.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./opensearch/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4318:4318 # OTLP http receiver
    


