version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 5678:5678 # to attach debug
      - 8000:8000 # actual webapp
    volumes:
      - ./backend/src/app:/usr/src/app
      - ./backend/src/tests:/usr/src/tests
      - ./backend/src/migrations/versions:/usr/src/migrations/versions

  cockroach:
    image: cockroachdb/cockroach-unstable:v21.2.0-beta.4
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257

  jupyter:
    build: ./jupyter
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks   
      - ./backend/src/app:/home/jovyan/backend/app:ro
    environment:
      PYTHONPATH: /home/jovyan/backend

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      # I'd love to just mount ./frontend/minor-illusion:/app
      # but it is volume hell with node_modules and .next directories
      - ./frontend/minor-illusion/src:/app/src
      - ./frontend/minor-illusion/public:/app/public
      - ./frontend/minor-illusion/package.json:/app/package.json
      - ./frontend/minor-illusion/yarn.lock:/app/yarn.lock

  docs:
    build: ./docs
    ports:
      - 8001:8000
    volumes:
      - ./docs/mkdocs:/usr/src/mkdocs
      


