"""Initial

Revision ID: 128a654019d2
Revises: 
Create Date: 2021-11-04 20:55:07.442666

"""
import uuid
from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "128a654019d2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    todo_table = op.create_table(
        "todo",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todo_id"), "todo", ["id"], unique=True)
    op.create_index(op.f("ix_todo_user_id"), "todo", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # Create seed data:
    # 3 Users: "user1", "user2", "user3".  All with password "pass"
    # 3 Todos all belonging to user1
    user1_uuid = uuid.uuid4()  # <- need to save this for Todo creation
    op.bulk_insert(
        user_table,
        [
            {
                "id": user1_uuid,
                "created_at": datetime.now(timezone.utc),
                "name": "user1",
                "password": "pass",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(timezone.utc),
                "name": "user2",
                "password": "pass",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(timezone.utc),
                "name": "user3",
                "password": "pass",
            },
        ],
    )

    op.bulk_insert(
        todo_table,
        [
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(timezone.utc),
                "title": "Note 1",
                "content": "My first Note",
                "user_id": user1_uuid,
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(timezone.utc),
                "title": "Note 2",
                "content": "Edit this Note",
                "user_id": user1_uuid,
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(timezone.utc),
                "title": "Note 3",
                "content": "Delete this Note",
                "user_id": user1_uuid,
            },
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todo_user_id"), table_name="todo")
    op.drop_index(op.f("ix_todo_id"), table_name="todo")
    op.drop_table("todo")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("users")
    # ### end Alembic commands ###
