# Static configuration for Traefik
# https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-static-configuration

entryPoints:
  web:
    address: ":5000"
  traefik:
    address: ":8081"

api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: ./dynamic

logs:
  level: DEBUG

accessLog: {}